run_name: default_experiment
batch_size: 5000
epochs: 2000
lr: 0.0001
weight_decay: 1e-6
num_workers: 8
hidden_dim: 64
data: training_data.npy
input_shape:
  - ndotl: 1
  - ndotv: 1
  - ndoth: 1
  - ldoth: 1
  - albedo: 3
  - roughness: 1
  - metallic: 1
save_dir: checkpoints/run4
save_interval: 5
mixed_precision: 'no'
# test